- name: Add repo
  yum:
    pkg: http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Enable repo
  shell: yum-config-manager --enable remi-php72

- name: Install Dependencies
  yum:
    pkg:
      - php
      - php-common
      - php-mbstring
      - php-gd
      - php-intl
      - php-xml
      - php-mysql
      - php-mcrypt
      - php-fpm

- name: enable php-fpm
  systemd:
    name: php-fpm
    enabled: true
    state: started
