- name: Enable IP Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: True

- name: Enable firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Enable NAT on firewall
  shell: |
    firewall-cmd --permanent --direct --passthrough ipv4 -t nat -I POSTROUTING -o eth0 -j MASQUERADE
    firewall-cmd --reload
